//
//  DummyAcademies.swift
//  MyDicodingProfile
//
//  Created by Fahmi on 13/05/20.
//  Copyright © 2020 Kementerian Agama Republik Indonesia. All rights reserved.
//

import UIKit

var academies: [Academy] = [
Academy(logo: UIImage(named: "java")!, name: "Memulai Pemrograman Dengan Java", stats: "100%", description: "Java is a language created by James Gosling in the 1990s. Java appears as a language that can run on various platforms without the need to re-compile. Based on the TIOBE Programming Community Index that reviews the popularity of programming languages, Java is still the number one programming language in the world. Data from Oracle states that 90% of leading companies included in the Fortune 500 list use Java. You can use Java to develop applications on desktop, web, mobile, to embedded and IoT platforms."),
Academy(logo: UIImage(named: "android_pemula")!, name: "Belajar Membuat Aplikasi Android untuk Pemula", stats: "Graduated", description: "Android is increasingly loved. As of March 2018, there were more than 3.6 million Android applications on the Google Play Store (Statista data). In Indonesia alone, in March 2019 93.5% of consumers chose the Android platform for their mobile device operating system (Statcounter data). This indicates that the need for Android developers is increasing. Not surprisingly, the Android developer profession is 1 of the 5 professions the most sought after by the company (LinkedIn Emerging Jobs Report 2019 data)."),
Academy(logo: UIImage(named: "android_expert")!, name: "Belajar Fundamental Aplikasi Android (Menjadi Android Developer Expert)", stats: "Graduated", description: "Android is increasingly loved. As of March 2018, there were more than 3.6 million Android applications on the Google Play Store (Statista data). In Indonesia alone, in March 2019 93.5% of consumers chose the Android platform for their mobile device operating system (Statcounter data). This indicates that the need for Android developers is increasing. Not surprisingly, the Android developer profession is 1 of the 5 professions the most sought after by the company (LinkedIn Emerging Jobs Report 2019 data)."),
Academy(logo: UIImage(named: "android_jetpack_pro")!, name: "Belajar Android Jetpack Pro", stats: "Graduated", description: "Jetpack Android is inspired by the Support Library, a set of components to facilitate the utilization of the latest Android features while maintaining compatibility with previous versions. Google introduces Architecture Components as part of Android Jetpack which is designed to facilitate the handling of data in the face of changes in the application life cycle. Since Google introduced in I / O 2018, a lot of IT companies have adopted it. Google states that Android Jetpack is used by 80% of the 1000 best Google Play Store applications. Companies such as LinkedIn, Traveloka, and Kakao Corporation (KakaoTalk) have found fewer bugs and successfully saved development time so they can focus more on what makes their application unique."),
Academy(logo: UIImage(named: "dasar_web")!, name: "Belajar Dasar Pemrograman Web", stats: "Graduated", description: "Website in this era has become a major need that cannot be ignored. All business or education sectors can use the website as a tool for promotion, information exchange, and others. As of January 2019, there were 1,518,207,413 active websites, based on a survey from the Webcraft Webserver Survey. Based on data from the World Wide Web Technology Surveys, from all active websites, 88.2% uses HTML, 95.6% uses CSS and 95% uses JavaScript."),
Academy(logo: UIImage(named: "liff")!, name: "Belajar Membangun LINE Front-end Framework (LIFF)", stats: "Graduated", description: "LINE is a communication platform that is in demand by many people, especially among teenagers. To date, of the total 220 million users worldwide, as many as 90 million are from Indonesia. The number of users is the fourth largest after Japan, Taiwan, and Thailand. LINE also has a front-end framework, known as the LINE Front-end Framework (LIFF). Using this framework allows you to be able to run web-based applications or games in the LINE application."),
Academy(logo: UIImage(named: "line_chatbot")!, name: "Belajar Membangun LINE Chatbot", stats: "Graduated", description: "LINE is a communication platform that is in demand by many people, especially among teenagers. To date, of the total 220 million users worldwide, as many as 90 million are from Indonesia. The number of users is the fourth largest after Japan, Taiwan, and Thailand. LINE also has LINE Chatbot which allows you to create bot-based chats that can be run on the LINE platform. A chatbot is an automated tool that can be used by brand or business accounts to create a 24-hour service presence in a variety of language and product types."),
Academy(logo: UIImage(named: "python")!, name: "Memulai Pemrograman Dengan Python", stats: "(was) 100%", description: "Python is an interpretive programming language that can be used on various platforms with a design philosophy that focuses on the level of code readability and is one of the popular languages related to Data Science, Machine Learning, and the Internet of Things (IoT). The advantages of interpretive Python are also widely used for prototyping, scripting in infrastructure management, to making large-scale websites. According to the journal Developer Economics - State of the Developer Nation, by the end of 2018, 69% of machine learning and data scientist developers were using Python. Besides, according to IEEE Spectrum in 2019, Python has retained its position as the most popular programming language in the world."),
Academy(logo: UIImage(named: "c")!, name: "Memulai Pemrograman Dengan C", stats: "100%", description: "C language is a procedural language that has many uses. It was designed to be compiled simply to support access to low-level memory, as language support that can be used in machine instructions, and to require minimal runtime support. Although it is designed at a minimum, C can be used as a multi-platform language. C language is perfect for those of you who want to enter the world of programming. C language is famous for its simple language so it's easy to learn. Therefore, C language is often used as the first language for learning programming. Based on data from Github, C language is one of the Top 10 Popular Languages."),
Academy(logo: UIImage(named: "swift")!, name: "Memulai Pemrograman Dengan Swift", stats: "Graduated", description: "Since it was introduced at the Apple Worldwide Developer Conference (WWDC) in 2014, Swift has become an official language supported by Apple Inc. for iOS, iPadOS, macOS, watchOS, tvOS, Linux, and OS X applications. Swift is a modern, fast, and type-safe programming language. By 2018, Swift had defeated Objective-C as a programming language used for iOS and other Apple platforms. According to a survey by Stack Overflow, Swift became the most preferred programming language in 2019. Compared to 2018, Swift lovers rose from 65% to 69%."),
Academy(logo: UIImage(named: "ios_pemula")!, name: "Belajar Membuat Aplikasi iOS untuk Pemula", stats: "(will be) Graduated", description: "Being an iOS developer is a dream job for many people. According to data from Indeed, one of the largest job search platforms in the world, the satisfaction level of being an iOS developer is 13% higher than that of the Android Developer profession. The iOS Developer Community Survey found that in 2020, 75.5% of developers still used a separate codebase when the application needed to be run on a variety of different platforms (such as Android and iOS OS). This means that many workplaces still want a separate codebase and are built from Xcode. Because of this, the industry demand for an iOS Developer is still very high even though the market share of iOS platform mobile users is only 26% (Statcounter data, February 2020).")
]
